// Complete menu data from the Acquaville PDF
window.ACQUA_DATA = {
  stations: [
    {
      id: 'restaurante',
      name: 'Restaurante',
      subtitle: 'do Acquaville',
      icon: '🍽️',
      emoji: '🍹',
      color: '#F39200',
      colorSoft: '#FFE6C5',
      hours: '10h — 18h',
      tagline: 'Sucos gelados e sobremesas',
      sections: [
        {
          name: 'SUCOS',
          items: [
            { name: 'Manga', price: 6.50, tags: ['bebida','sem-alcool'] },
            { name: 'Morango', price: 6.50, tags: ['bebida','sem-alcool'], featured: true },
            { name: 'Abacaxi (com ou sem hortelã)', price: 6.50, tags: ['bebida','sem-alcool'] },
            { name: 'Maracujá', price: 6.50, tags: ['bebida','sem-alcool'] },
          ],
        },
        {
          name: 'SOBREMESAS',
          items: [
            { name: 'Pudim', price: 8, tags: ['doce'] },
            { name: 'Doce de leite', price: 8, tags: ['doce'] },
            { name: 'Bolo de pote', price: 10, tags: ['doce'], featured: true },
            { name: 'Delícia de morango', price: 10, tags: ['doce'], featured: true },
          ],
        },
      ],
    },
    {
      id: 'lanchonete',
      name: 'Lanchonete',
      subtitle: 'do Acquaville',
      icon: '🍦',
      emoji: '🍧',
      color: '#00AEEF',
      colorSoft: '#CFF0FB',
      hours: '09h — 19h',
      tagline: 'Picolés, sundaes e petiscos',
      sections: [
        {
          name: 'PICOLÉS',
          items: [
            { name: 'Picolé Black', price: 12, tags: ['doce'], featured: true },
            { name: 'Picolé Brigadeiro', price: 8, tags: ['doce'] },
            { name: 'Picolé Coração', price: 8, tags: ['doce'] },
            { name: 'Picolé Limão', price: 4, tags: ['doce'] },
            { name: 'Picolé Morango', price: 4, tags: ['doce'] },
            { name: 'Picolé Tentação', price: 8, tags: ['doce'] },
            { name: 'Picolé Trufado Nata Goiaba', price: 6, tags: ['doce'] },
            { name: 'Picolé Unicórnio', price: 8, tags: ['doce'], featured: true },
            { name: 'Picolé Uva', price: 4, tags: ['doce'] },
            { name: 'Quy Cone Brigadeiro', price: 11, tags: ['doce'] },
            { name: 'Quy Cone Torpedo', price: 11, tags: ['doce'] },
            { name: 'Quy Dueto · Açaí + Leitinho', price: 6, tags: ['doce'] },
            { name: 'Quy Frutti Morango', price: 5, tags: ['doce'] },
            { name: 'Quy Lack · Leite', price: 8, tags: ['doce'] },
            { name: 'Quy Milk Leite Condensado', price: 4.50, tags: ['doce'] },
            { name: 'Quy Milk Tapioca com Coco', price: 4.50, tags: ['doce'] },
            { name: 'Sundae', price: 8, tags: ['doce'], featured: true },
          ],
        },
        {
          name: 'BEBIDAS',
          items: [
            { name: 'Água Mineral com gás 500ml', price: 4, tags: ['bebida','sem-alcool'] },
            { name: 'Água Mineral sem gás 500ml', price: 3, tags: ['bebida','sem-alcool'] },
            { name: 'Amstel Lata 350ml', price: 6.50, tags: ['bebida','com-alcool'] },
            { name: 'Guaraná Antarctica Lata', price: 6, tags: ['bebida','sem-alcool'] },
            { name: 'Guaraná Antarctica Zero Lata', price: 6, tags: ['bebida','sem-alcool'] },
            { name: 'Pepsi Lata', price: 6, tags: ['bebida','sem-alcool'] },
            { name: 'Soda Limonada Lata', price: 4, tags: ['bebida','sem-alcool'] },
            { name: 'Sukita Lata', price: 6, tags: ['bebida','sem-alcool'] },
            { name: 'Suco de Manga', price: 4, tags: ['bebida','sem-alcool'] },
            { name: 'Suco de Maracujá', price: 4, tags: ['bebida','sem-alcool'] },
            { name: 'Suco de Uva', price: 4, tags: ['bebida','sem-alcool'] },
          ],
        },
        {
          name: 'OUTROS',
          items: [
            { name: 'Batata Hyts Churrasco', price: 5, tags: ['salgado'] },
            { name: 'Batata Hyts Natural', price: 5, tags: ['salgado'] },
            { name: 'Cremosinho Leite Condensado', price: 2.50, tags: ['doce'] },
            { name: 'Cremosinho Maracujá', price: 2.50, tags: ['doce'] },
            { name: 'Cremosinho Morango', price: 2.50, tags: ['doce'] },
            { name: 'Pé de Moleque', price: 8, tags: ['doce'] },
            { name: 'Plic Pimentinha', price: 5, tags: ['salgado'] },
            { name: 'Plinc Pipoca Salgada', price: 4, tags: ['salgado'] },
            { name: 'Plinc Pururuca Pequeno Costela', price: 3, tags: ['salgado'] },
            { name: 'Plinc Pururuca Pequeno Tradicional', price: 3, tags: ['salgado'] },
            { name: 'Salgados Diversos', price: 8, tags: ['salgado'], featured: true },
          ],
        },
      ],
    },
    {
      id: 'doces',
      name: 'Doces da Mara',
      subtitle: '',
      icon: '🍭',
      emoji: '🍫',
      color: '#E62E4D',
      colorSoft: '#FFD4DC',
      hours: '10h — 19h',
      tagline: 'Algodão doce, brigadeiros e mais',
      sections: [
        {
          name: 'DOCES',
          items: [
            { name: 'Algodão doce no palito', price: 8, tags: ['doce'], featured: true },
            { name: 'Algodão doce no pote', price: 10, tags: ['doce'] },
            { name: 'Amendoim torrado', price: 6, tags: ['doce'] },
            { name: 'Bala baiana', price: 6, tags: ['doce'] },
            { name: 'Brigadeiros', price: 3, tags: ['doce'], featured: true },
            { name: 'Bolo no pote', price: 12, tags: ['doce'] },
            { name: 'Chiclete', price: 1, tags: ['doce'] },
            { name: 'Churros', price: 8, tags: ['doce'], featured: true },
            { name: 'Doce de leite', price: 10, tags: ['doce'] },
            { name: 'Donut', price: 6, tags: ['doce'] },
            { name: 'Fondue de morango', price: 10, tags: ['doce'] },
            { name: 'Jujuba', price: 2, tags: ['doce'] },
            { name: 'Maçã do amor', price: 10, tags: ['doce'] },
            { name: 'Morango do amor', price: 15, tags: ['doce'], featured: true },
            { name: 'Mousse de maracujá', price: 8, tags: ['doce'] },
            { name: 'Pipoca grande', price: 6, tags: ['salgado'] },
            { name: 'Pipoca pequena', price: 4, tags: ['salgado'] },
            { name: 'Pipoca gourmet', price: 12, tags: ['salgado'] },
            { name: 'Pirulito grande', price: 10, tags: ['doce'] },
            { name: 'Pirulito pequeno', price: 5, tags: ['doce'] },
            { name: 'Torta de chocolate', price: 15, tags: ['doce'] },
            { name: 'Torta de limão', price: 15, tags: ['doce'] },
            { name: 'Pipoca colorida', price: 8, tags: ['salgado'] },
            { name: 'Pudim', price: 10, tags: ['doce'] },
          ],
        },
      ],
    },
    {
      id: 'petisco',
      name: 'Point do Petisco',
      subtitle: '',
      icon: '🍟',
      emoji: '🍗',
      color: '#F5A623',
      colorSoft: '#FFEACB',
      hours: '11h — 20h',
      tagline: 'Batatas, coxinhas e combos',
      sections: [
        {
          name: 'BATATAS E PORÇÕES',
          items: [
            { name: 'Batata frita 400g', price: 30, tags: ['salgado'], featured: true },
            { name: 'Batata com cheddar 400g', price: 35, tags: ['salgado'], featured: true },
            { name: 'Camarão encapotado 5 un', price: 35, tags: ['salgado'] },
          ],
        },
        {
          name: 'COXINHAS · 12 un',
          items: [
            { name: 'Frango', price: 25, tags: ['salgado'] },
            { name: 'Quatro queijos', price: 25, tags: ['salgado'] },
            { name: 'Peito de peru', price: 25, tags: ['salgado'] },
            { name: 'Calabresa', price: 25, tags: ['salgado'] },
            { name: 'Calabresa Toscana', price: 25, tags: ['salgado'] },
          ],
        },
        {
          name: 'COMBOS DE COXINHAS',
          items: [
            { name: 'Combo 1 · 3 sabores 12 un', price: 25, tags: ['salgado'] },
            { name: 'Combo 2 · 5 sabores 20 un', price: 40, tags: ['salgado'], featured: true },
          ],
        },
      ],
    },
    {
      id: 'acquaraje',
      name: 'Point do Acquarajé',
      subtitle: '',
      icon: '🥙',
      emoji: '🌶️',
      color: '#D94B1F',
      colorSoft: '#FFD4C2',
      hours: '11h — 19h',
      tagline: 'Acarajé e porções',
      sections: [
        {
          name: 'PORÇÕES',
          items: [
            { name: 'Acarajé individual com camarão', price: 26, tags: ['salgado'], featured: true },
            { name: 'Acarajé individual sem camarão', price: 23.40, tags: ['salgado'] },
            { name: 'Porção 13 bolinhos com camarão', price: 39.40, tags: ['salgado'] },
            { name: 'Porção 13 bolinhos sem camarão', price: 32.50, tags: ['salgado'] },
            { name: 'Porção 23 bolinhos com camarão', price: 58.50, tags: ['salgado'] },
            { name: 'Porção 23 bolinhos sem camarão', price: 52, tags: ['salgado'] },
            { name: 'Porção 33 bolinhos com camarão', price: 71.50, tags: ['salgado'], featured: true },
            { name: 'Porção 33 bolinhos sem camarão', price: 65, tags: ['salgado'] },
          ],
        },
      ],
    },
    {
      id: 'acai',
      name: 'Point do Açaí',
      subtitle: '',
      icon: '🍇',
      emoji: '🫐',
      color: '#E91E9E',
      colorSoft: '#FFD6EC',
      hours: '10h — 19h',
      tagline: 'Açaí cremoso e milk shakes',
      sections: [
        {
          name: 'AÇAÍ & BEBIDAS',
          items: [
            { name: 'Açaí 400ml', price: 25, tags: ['doce'], featured: true },
            { name: 'Milk Shake 500ml', price: 25, tags: ['doce','bebida'], featured: true },
            { name: 'Água mineral 500ml', price: 3, tags: ['bebida','sem-alcool'] },
            { name: 'Água mineral com gás 500ml', price: 4, tags: ['bebida','sem-alcool'] },
            { name: 'Açaí zero 400ml', price: 30, tags: ['doce'] },
          ],
        },
      ],
    },
    {
      id: 'bar',
      name: 'Bar Molhado',
      subtitle: '',
      icon: '🍹',
      emoji: '🍸',
      color: '#FFC107',
      colorSoft: '#FFF2C2',
      hours: '11h — 22h',
      tagline: 'Drinks com e sem álcool',
      sections: [
        {
          name: 'DRINKS COM ÁLCOOL',
          items: [
            { name: 'Caipirinha', price: 18, tags: ['bebida','com-alcool'], desc: 'Limão, açúcar, cachaça e gelo.', featured: true },
            { name: 'Caipiroska de Frutas', price: 26, tags: ['bebida','com-alcool'], desc: 'Morango ou abacaxi, vodka, açúcar e gelo.' },
            { name: 'Mojito', price: 25, tags: ['bebida','com-alcool'], desc: 'Hortelã, limão, açúcar, rum, água com gás e gelo.', featured: true },
            { name: 'Gin Tônica', price: 25, tags: ['bebida','com-alcool'], desc: 'Gin, tônica ou soda, xarope saborizado e gelo.' },
            { name: 'Sex on the Beach', price: 28, tags: ['bebida','com-alcool'], desc: 'Vodka, licor de pêssego, xarope de frutas vermelhas, suco de laranja e gelo.', featured: true },
            { name: 'Acqua Old Bale', price: 30, tags: ['bebida','com-alcool'], desc: 'Whisky Old Parr, hortelã, açúcar e xarope de tangerina.' },
            { name: 'Garibaldi', price: 22, tags: ['bebida','com-alcool'], desc: 'Campari, suco de laranja e gelo.' },
            { name: 'Whisky Citrus', price: 28, tags: ['bebida','com-alcool'], desc: 'Whisky Red Label, suco de limão, gelo e água com gás ou soda.' },
            { name: 'Moscow Mule', price: 25, tags: ['bebida','com-alcool'], desc: 'Vodka, xarope de gengibre, limão, espuma de gengibre e gelo.' },
            { name: 'Lagoa Azul', price: 25, tags: ['bebida','com-alcool'], desc: 'Vodka, licor de curaçau blue, limão, soda e gelo.' },
          ],
        },
        {
          name: 'DRINKS SEM ÁLCOOL',
          items: [
            { name: 'Citrus', price: 15, tags: ['bebida','sem-alcool'], desc: 'Limão, hortelã, açúcar, água com gás e gelo.' },
            { name: 'Laranja Splash', price: 20, tags: ['bebida','sem-alcool'], desc: 'Suco de laranja, água com gás, gelo e laranja.' },
            { name: 'Morango Refrescante', price: 18, tags: ['bebida','sem-alcool'], desc: 'Xarope de morango, limão, água com gás e gelo.', featured: true },
            { name: 'Maçã Verde Tônica', price: 18, tags: ['bebida','sem-alcool'], desc: 'Xarope de maçã verde, água tônica e limão.' },
            { name: 'Tangerina Mix', price: 18, tags: ['bebida','sem-alcool'], desc: 'Xarope de tangerina, suco de laranja e gelo.' },
            { name: 'Frutas Vermelhas Soda', price: 18, tags: ['bebida','sem-alcool'], desc: 'Xarope de frutas vermelhas, soda limonada e laranja.' },
          ],
        },
        {
          name: 'GELADOS',
          items: [
            { name: 'Água com gás', price: 4, tags: ['bebida','sem-alcool'] },
            { name: 'Água de coco', price: 8, tags: ['bebida','sem-alcool'] },
            { name: 'Água sem gás', price: 3, tags: ['bebida','sem-alcool'] },
            { name: 'Amstel lata', price: 6.50, tags: ['bebida','com-alcool'] },
            { name: 'Chopp Heineken 430ml', price: 15, tags: ['bebida','com-alcool'], featured: true },
            { name: 'Gatorade', price: 10, tags: ['bebida','sem-alcool'] },
            { name: 'H2O', price: 7, tags: ['bebida','sem-alcool'] },
            { name: 'Heineken 0% álcool lata', price: 8.50, tags: ['bebida','sem-alcool'] },
            { name: 'Heineken lata', price: 8.50, tags: ['bebida','com-alcool'] },
            { name: 'Red Bull', price: 15, tags: ['bebida','sem-alcool'] },
            { name: 'Refrigerante', price: 6, tags: ['bebida','sem-alcool'] },
            { name: 'Skol Beats', price: 10, tags: ['bebida','com-alcool'] },
          ],
        },
        {
          name: 'COMBOS',
          items: [
            { name: 'Combo Amstel (6 unidades)', price: 36, tags: ['bebida','com-alcool'], featured: true },
            { name: 'Combo Heineken (6 unidades)', price: 48, tags: ['bebida','com-alcool'], featured: true },
          ],
        },
        {
          name: 'DESTILADOS',
          items: [
            { name: 'Campari', price: 12, tags: ['bebida','com-alcool'] },
            { name: 'Cachaça Asa Branca', price: 8, tags: ['bebida','com-alcool'] },
            { name: 'Cachaça Seleta', price: 8, tags: ['bebida','com-alcool'] },
            { name: 'Gin Bombay Sapphire', price: 20, tags: ['bebida','com-alcool'] },
            { name: "Gin Gordon's", price: 15, tags: ['bebida','com-alcool'] },
            { name: 'Licor 43', price: 25, tags: ['bebida','com-alcool'] },
            { name: 'Tequila', price: 18, tags: ['bebida','com-alcool'] },
            { name: 'Vodka Absolut', price: 15, tags: ['bebida','com-alcool'] },
            { name: 'Vodka Smirnoff', price: 12, tags: ['bebida','com-alcool'] },
            { name: 'Whisky Chivas', price: 20, tags: ['bebida','com-alcool'] },
            { name: 'Whisky Old Parr', price: 20, tags: ['bebida','com-alcool'] },
            { name: 'Whisky Red Label', price: 15, tags: ['bebida','com-alcool'] },
          ],
        },
      ],
    },
    {
      id: 'espetinho',
      name: 'Espetinho',
      subtitle: 'do Acquaville',
      icon: '🍢',
      emoji: '🔥',
      color: '#D94B1F',
      colorSoft: '#FFD4C2',
      hours: '12h — 20h',
      tagline: 'Grelhados na brasa',
      sections: [
        {
          name: 'ESPETINHOS · Sabores',
          items: [
            { name: 'Bovino', price: 14, tags: ['salgado'], featured: true },
            { name: 'Suíno', price: 14, tags: ['salgado'] },
            { name: 'Medalhão de Frango', price: 14, tags: ['salgado'], featured: true },
            { name: 'Coração', price: 14, tags: ['salgado'] },
            { name: 'Carneiro', price: 14, tags: ['salgado'] },
            { name: 'Queijo Coalho', price: 14, tags: ['salgado'], featured: true },
          ],
        },
      ],
    },
  ],
};
